version: '3.8'

services:
  server:
    build: ./server
    container_name: realstate-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
